### ISSUE TITLE
[Bazel CI]  Generating proto for Starlark doc for defs failed:


### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_proto#223]
CI: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4026#01910c21-52f1-4035-b660-2df32df053eb

 Platform: MacOS

 Logs: 
```
ERROR: /Users/buildkite/builds/bk-macos-pln3-i0oq/bazel-org-repo-root/rules_proto/docs/BUILD:3:23: Generating proto for Starlark doc for defs failed: (Exit 1): defs_stardoc failed: error executing Stardoc command (from target //docs:defs)
  (cd /private/var/tmp/_bazel_buildkite/a960038a25de9e350b0c602fdd7e68cb/sandbox/darwin-sandbox/13/execroot/_main && \
  exec env - \
  bazel-out/darwin_x86_64-opt-exec-ST-d57f47055a04/bin/docs/defs_stardoc '--input=@@//proto:defs.bzl' '--workspace_name=_main' '--output=bazel-out/darwin_x86_64-fastbuild/bin/docs/docs/defs.raw')
# Configuration: b2ddbb31c7311492ec11003d5d3cc590f619dcbf066a334af1913b9fa02c1273
# Execution platform: @@platforms//host:host
Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
Exception in thread "main" java.lang.IllegalArgumentException: com.google.devtools.build.lib.cmdline.LabelSyntaxException: invalid repository name '@protobuf+': repo names may contain only A-Z, a-z, 0-9, '-', '_', '.' and '~' and must not start with '~'
	at com.google.devtools.build.lib.cmdline.Label.parseCanonicalUnchecked(Label.java:152)
	at com.google.devtools.build.skydoc.SkydocMain.toCanonicalLabel(SkydocMain.java:491)
	at com.google.devtools.build.skydoc.SkydocMain.recursiveEval(SkydocMain.java:447)
	at com.google.devtools.build.skydoc.SkydocMain.eval(SkydocMain.java:289)
	at com.google.devtools.build.skydoc.SkydocMain.main(SkydocMain.java:151)
Caused by: com.google.devtools.build.lib.cmdline.LabelSyntaxException: invalid repository name '@protobuf+': repo names may contain only A-Z, a-z, 0-9, '-', '_', '.' and '~' and must not start with '~'
	at com.google.devtools.build.lib.cmdline.LabelParser.syntaxErrorf(LabelParser.java:208)
	at com.google.devtools.build.lib.cmdline.RepositoryName.validate(RepositoryName.java:160)
	at com.google.devtools.build.lib.cmdline.LabelParser$Parts.validateRepoName(LabelParser.java:180)
	at com.google.devtools.build.lib.cmdline.LabelParser$Parts.validateAndCreate(LabelParser.java:72)
	at com.google.devtools.build.lib.cmdline.LabelParser$Parts.parse(LabelParser.java:164)
	at com.google.devtools.build.lib.cmdline.Label.parseCanonical(Label.java:138)
	at com.google.devtools.build.lib.cmdline.Label.parseCanonicalUnchecked(Label.java:150)
	... 4 more
(06:12:50) INFO: Elapsed time: 71.771s, Critical Path: 7.44s
(06:12:50) INFO: 584 processes: 3 remote cache hit, 573 internal, 6 darwin-sandbox, 2 worker.
(06:12:50) ERROR: Build did NOT complete successfully
``` 
 Culprit: 

 Steps:
  ``` 
 git clone https://github.com/bazelbuild/rules_proto
git reset 557db790e7a71993ff85bf523099dfd25060ae2f  --hard
export USE_BAZEL_VERSION=a7264d99e2d14463cb683a4091d5ad0e08431205
bazel build //... 
 ``` 
 CC Greenteam @fweikert

**Comment by sgowroji** [comment]
CC @Yannic

**Comment by comius** [comment]
cc @Wyverald @meteorcloudy 
This looks related to change of ~ to + in canonical repo names.
